### ISSUE TITLE
I don’t understand how to use ReplayMap for  6 !!!

### ISSUE THREAD

**Issue by Real1Maks** [SamuelH91/Civ6EGRM#1]
You see, I'm a beginner in python and it's still difficult for me to work with codes, but I really need this mod. I have been waiting for him for 4 years. And then a great opportunity appeared, but suddenly difficult tasks interfere ...
Can you describe or show in more detail what and how to do?
Or maybe we will contact you on a social network (Discord, Facebook, VK)? We'll talk there!;)

**Comment by SamuelH91** [comment]
Add me on Discord Lapwing#2299 and we can look into it at some point
