### ISSUE TITLE
KeyError 24

### ISSUE THREAD

**Issue by Nosceteipsum** [SamuelH91/Civ6EGRM#5]
When I run endGameReplay.py I get this error: 

![image](https://user-images.githubusercontent.com/7213547/128890910-34498ad7-7e59-4846-933a-a3b36ad59752.png)

I have attached 2 .save game files to replicate the error.
[auto.zip](https://github.com/SamuelH91/Civ6EGRM/files/6962641/auto.zip)

**Comment by SamuelH91** [comment]
I will look into it

**Comment by SamuelH91** [comment]
Should be fixed now. You can update via git commands or with nonGitUpdater.py code.

**Comment by Nosceteipsum** [comment]
Yeah, it works. 
Thank you for the quick help.
