### ISSUE TITLE
IndexError - list index out of range

### ISSUE THREAD

**Issue by Nosceteipsum** [SamuelH91/Civ6EGRM#6]
When I run endGameReplay.py I get this error:
![image](https://user-images.githubusercontent.com/7213547/129081894-08dbb89c-7796-4b6b-a858-43e4ef531675.png)

I have attached 2 .save game files to replicate the error.
[auto.zip](https://github.com/SamuelH91/Civ6EGRM/files/6970552/auto.zip)

**Comment by Nosceteipsum** [comment]
Hi @SamuelH91 ,
Note this is a new error with files **AutoSave_0153** to **AutoSave_0154.** 

You fixed another error with save files **AutoSave_164** to **AutoSave_165** in issue case 5: https://github.com/SamuelH91/Civ6EGRM/issues/5

**Comment by SamuelH91** [comment]
Ok

**Comment by SamuelH91** [comment]
Should be fixed

**Comment by Nosceteipsum** [comment]
Yeah, it works.
Thank you for the quick help.
