### ISSUE TITLE
IndexError - list index out of range 0199-0200

### ISSUE THREAD

**Issue by Nosceteipsum** [SamuelH91/Civ6EGRM#7]
Sorry, got one more error:
![image](https://user-images.githubusercontent.com/7213547/129097394-24462327-8bdf-49c3-91a4-f42ae7f1f4d1.png)

I have attached 2 .save game files to replicate the error.
**AutoSave_0199** - **AutoSave_0200**
[auto.zip](https://github.com/SamuelH91/Civ6EGRM/files/6971164/auto.zip)

**Comment by SamuelH91** [comment]
Someone bullied a city state, but a hero strike back and liberated it. Should be fixed now.

**Comment by Nosceteipsum** [comment]
It works perfect, thank you. 
![endGameReplayMap](https://user-images.githubusercontent.com/7213547/129317907-0ec1d897-233e-40b8-b850-7faff43f60b8.gif)
